/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AggTrade
 */
export interface AggTrade {

    /**
     * Aggregate tradeId
     *
     * @type {number}
     * @memberof AggTrade
     * @example 26129
     */
    a: number;

    /**
     * Price
     *
     * @type {string}
     * @memberof AggTrade
     * @example 0.01633102
     */
    p: string;

    /**
     * Quantity
     *
     * @type {string}
     * @memberof AggTrade
     * @example 4.70443515
     */
    q: string;

    /**
     * First tradeId
     *
     * @type {number}
     * @memberof AggTrade
     * @example 27781
     */
    f: number;

    /**
     * Last tradeId
     *
     * @type {number}
     * @memberof AggTrade
     * @example 27781
     */
    l: number;

    /**
     * Timestamp
     *
     * @type {boolean}
     * @memberof AggTrade
     * @example false
     */
    T: boolean;

    /**
     * Was the buyer the maker?
     *
     * @type {boolean}
     * @memberof AggTrade
     */
    m: boolean;

    /**
     * Was the trade the best price match?
     *
     * @type {boolean}
     * @memberof AggTrade
     */
    M: boolean;
}
