/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface BookTicker
 */
export interface BookTicker {

    /**
     * @type {string}
     * @memberof BookTicker
     * @example BNBBTC
     */
    symbol: string;

    /**
     * @type {string}
     * @memberof BookTicker
     * @example 16.36240000
     */
    bidPrice: string;

    /**
     * @type {string}
     * @memberof BookTicker
     * @example 256.78000000
     */
    bidQty: string;

    /**
     * @type {string}
     * @memberof BookTicker
     * @example 16.36450000
     */
    askPrice: string;

    /**
     * @type {string}
     * @memberof BookTicker
     * @example 12.56000000
     */
    askQty: string;
}
