/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface BswapAddLiquidityPreviewSingle
 */
export interface BswapAddLiquidityPreviewSingle {

    /**
     * @type {string}
     * @memberof BswapAddLiquidityPreviewSingle
     * @example USDT
     */
    quoteAsset: string;

    /**
     * @type {number}
     * @memberof BswapAddLiquidityPreviewSingle
     * @example 300000
     */
    quoteAmt: number;

    /**
     * @type {number}
     * @memberof BswapAddLiquidityPreviewSingle
     * @example 1.00008334
     */
    price: number;

    /**
     * @type {number}
     * @memberof BswapAddLiquidityPreviewSingle
     * @example 1.23
     */
    share: number;

    /**
     * @type {number}
     * @memberof BswapAddLiquidityPreviewSingle
     * @example 0.00007245
     */
    slippage: number;

    /**
     * @type {number}
     * @memberof BswapAddLiquidityPreviewSingle
     * @example 120
     */
    fee: number;
}
