/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface BswapRmvLiquidityPreviewCombination
 */
export interface BswapRmvLiquidityPreviewCombination {

    /**
     * @type {string}
     * @memberof BswapRmvLiquidityPreviewCombination
     * @example USDT
     */
    quoteAsset: string;

    /**
     * @type {string}
     * @memberof BswapRmvLiquidityPreviewCombination
     * @example BUSD
     */
    baseAsset: string;

    /**
     * @type {number}
     * @memberof BswapRmvLiquidityPreviewCombination
     * @example 300000
     */
    quoteAmt: number;

    /**
     * @type {number}
     * @memberof BswapRmvLiquidityPreviewCombination
     * @example 299975
     */
    baseAmt: number;

    /**
     * @type {number}
     * @memberof BswapRmvLiquidityPreviewCombination
     * @example 1.00008334
     */
    price: number;
}
