/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200272Rows
 */
export interface InlineResponse200272Rows {

    /**
     * @type {string}
     * @memberof InlineResponse200272Rows
     * @example BUSD001
     */
    productId: string;

    /**
     * @type {string}
     * @memberof InlineResponse200272Rows
     * @example BUSD
     */
    asset: string;

    /**
     * @type {string}
     * @memberof InlineResponse200272Rows
     * @example 0.00006408
     */
    annualPercentageRate: string;

    /**
     * @type {number}
     * @memberof InlineResponse200272Rows
     * @example 1577233578000
     */
    time: number;
}
