/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse200261Rows } from './inline-response200261-rows';
 /**
 * 
 *
 * @export
 * @interface InlineResponse200261
 */
export interface InlineResponse200261 {

    /**
     * @type {Array<InlineResponse200261Rows>}
     * @memberof InlineResponse200261
     */
    rows: Array<InlineResponse200261Rows>;

    /**
     * @type {number}
     * @memberof InlineResponse200261
     * @example 1
     */
    total: number;
}
