/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse200156Orders } from './inline-response200156-orders';
 /**
 * 
 *
 * @export
 * @interface InlineResponse200156
 */
export interface InlineResponse200156 {

    /**
     * @type {number}
     * @memberof InlineResponse200156
     * @example 1
     */
    total: number;

    /**
     * @type {Array<InlineResponse200156Orders>}
     * @memberof InlineResponse200156
     */
    orders: Array<InlineResponse200156Orders>;
}
