/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse200113DataAssets } from './inline-response200113-data-assets';
import { InlineResponse200113DataPosition } from './inline-response200113-data-position';
 /**
 * 
 *
 * @export
 * @interface InlineResponse200113Data
 */
export interface InlineResponse200113Data {

    /**
     * @type {Array<InlineResponse200113DataAssets>}
     * @memberof InlineResponse200113Data
     */
    assets: Array<InlineResponse200113DataAssets>;

    /**
     * @type {Array<InlineResponse200113DataPosition>}
     * @memberof InlineResponse200113Data
     */
    position: Array<InlineResponse200113DataPosition>;
}
