/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20068Rows
 */
export interface InlineResponse20068Rows {

    /**
     * @type {number}
     * @memberof InlineResponse20068Rows
     * @example 242006910
     */
    id: number;

    /**
     * @type {string}
     * @memberof InlineResponse20068Rows
     * @example 10.00000000
     */
    amount: string;

    /**
     * @type {string}
     * @memberof InlineResponse20068Rows
     * @example BHFT
     */
    asset: string;

    /**
     * @type {number}
     * @memberof InlineResponse20068Rows
     * @example 1563189166000
     */
    divTime: number;

    /**
     * @type {string}
     * @memberof InlineResponse20068Rows
     * @example BHFT distribution
     */
    enInfo: string;

    /**
     * @type {number}
     * @memberof InlineResponse20068Rows
     * @example 2968885920
     */
    tranId: number;
}
