/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200135
 */
export interface InlineResponse200135 {

    /**
     * @type {string}
     * @memberof InlineResponse200135
     * @example 123123
     */
    positionId: string;

    /**
     * @type {number}
     * @memberof InlineResponse200135
     * @example 1575018510000
     */
    time: number;

    /**
     * @type {string}
     * @memberof InlineResponse200135
     * @example BNB
     */
    asset: string;

    /**
     * @type {string}
     * @memberof InlineResponse200135
     * @example BSC
     */
    project: string;

    /**
     * @type {string}
     * @memberof InlineResponse200135
     * @example 21312.23223
     */
    amount: string;

    /**
     * @type {string}
     * @memberof InlineResponse200135
     * @example 30
     */
    lockPeriod: string;

    /**
     * @type {string}
     * @memberof InlineResponse200135
     * @example 1575018510000
     */
    deliverDate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200135
     * @example AUTO
     */
    type: string;

    /**
     * @type {string}
     * @memberof InlineResponse200135
     * @example success
     */
    status: string;
}
