/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20082
 */
export interface InlineResponse20082 {

    /**
     * @type {string}
     * @memberof InlineResponse20082
     * @example aaa@test.com
     */
    from: string;

    /**
     * @type {string}
     * @memberof InlineResponse20082
     * @example bbb@test.com
     */
    to: string;

    /**
     * @type {string}
     * @memberof InlineResponse20082
     * @example BTC
     */
    asset: string;

    /**
     * @type {string}
     * @memberof InlineResponse20082
     * @example 10
     */
    qty: string;

    /**
     * @type {string}
     * @memberof InlineResponse20082
     * @example SUCCESS
     */
    status: string;

    /**
     * @type {number}
     * @memberof InlineResponse20082
     * @example 6489943656
     */
    tranId: number;

    /**
     * @type {number}
     * @memberof InlineResponse20082
     * @example 1544433328000
     */
    time: number;
}
