/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200210Rows
 */
export interface InlineResponse200210Rows {

    /**
     * @type {string}
     * @memberof InlineResponse200210Rows
     * @example BUSD
     */
    loanCoin: string;

    /**
     * @type {string}
     * @memberof InlineResponse200210Rows
     * @example 0.00000491
     */
    _7dHourlyInterestRate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200210Rows
     * @example 0.000118
     */
    _7dDailyInterestRate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200210Rows
     * @example 0.00000491
     */
    _14dHourlyInterestRate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200210Rows
     * @example 0.000118
     */
    _14dDailyInterestRate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200210Rows
     * @example 0.00000567
     */
    _30dHourlyInterestRate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200210Rows
     * @example 0.000136
     */
    _30dDailyInterestRate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200210Rows
     * @example 0.00000596
     */
    _90dHourlyInterestRate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200210Rows
     * @example 0.000143
     */
    _90dDailyInterestRate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200210Rows
     * @example 0.00000631
     */
    _180dHourlyInterestRate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200210Rows
     * @example 0.000151
     */
    _180dDailyInterestRate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200210Rows
     * @example 100
     */
    minLimit: string;

    /**
     * @type {string}
     * @memberof InlineResponse200210Rows
     * @example 1000000
     */
    maxLimit: string;

    /**
     * @type {number}
     * @memberof InlineResponse200210Rows
     * @example 1
     */
    vipLevel: number;
}
