/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20010OrderReports
 */
export interface InlineResponse20010OrderReports {

    /**
     * @type {string}
     * @memberof InlineResponse20010OrderReports
     */
    symbol: string;

    /**
     * @type {number}
     * @memberof InlineResponse20010OrderReports
     */
    orderId: number;

    /**
     * @type {number}
     * @memberof InlineResponse20010OrderReports
     */
    orderListId: number;

    /**
     * @type {string}
     * @memberof InlineResponse20010OrderReports
     */
    clientOrderId: string;

    /**
     * @type {number}
     * @memberof InlineResponse20010OrderReports
     */
    transactTime: number;

    /**
     * @type {string}
     * @memberof InlineResponse20010OrderReports
     */
    price: string;

    /**
     * @type {string}
     * @memberof InlineResponse20010OrderReports
     */
    origQty: string;

    /**
     * @type {string}
     * @memberof InlineResponse20010OrderReports
     */
    executedQty: string;

    /**
     * @type {string}
     * @memberof InlineResponse20010OrderReports
     */
    cummulativeQuoteQty: string;

    /**
     * @type {string}
     * @memberof InlineResponse20010OrderReports
     */
    status: string;

    /**
     * @type {string}
     * @memberof InlineResponse20010OrderReports
     */
    timeInForce: string;

    /**
     * @type {string}
     * @memberof InlineResponse20010OrderReports
     */
    type: string;

    /**
     * @type {string}
     * @memberof InlineResponse20010OrderReports
     */
    side: string;

    /**
     * @type {string}
     * @memberof InlineResponse20010OrderReports
     */
    stopPrice: string;

    /**
     * @type {string}
     * @memberof InlineResponse20010OrderReports
     */
    workingTime: string;

    /**
     * @type {string}
     * @memberof InlineResponse20010OrderReports
     */
    selfTradePreventionMode: string;
}
