/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse200239Data } from './inline-response200239-data';
 /**
 * 
 *
 * @export
 * @interface InlineResponse200239
 */
export interface InlineResponse200239 {

    /**
     * @type {string}
     * @memberof InlineResponse200239
     * @example 000000
     */
    code: string;

    /**
     * @type {string}
     * @memberof InlineResponse200239
     * @example success
     */
    message: string;

    /**
     * @type {InlineResponse200239Data}
     * @memberof InlineResponse200239
     */
    data: InlineResponse200239Data;

    /**
     * @type {boolean}
     * @memberof InlineResponse200239
     */
    success: boolean;
}
