/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200103
 */
export interface InlineResponse200103 {

    /**
     * @type {number}
     * @memberof InlineResponse200103
     * @example 11945860693
     */
    tranId: number;

    /**
     * @type {string}
     * @memberof InlineResponse200103
     * @example master@test.com
     */
    fromEmail: string;

    /**
     * @type {string}
     * @memberof InlineResponse200103
     * @example subaccount1@test.com
     */
    toEmail: string;

    /**
     * @type {string}
     * @memberof InlineResponse200103
     * @example BTC
     */
    asset: string;

    /**
     * @type {string}
     * @memberof InlineResponse200103
     * @example 0.1
     */
    amount: string;

    /**
     * @type {string}
     * @memberof InlineResponse200103
     * @example SPOT
     */
    fromAccountType: string;

    /**
     * @type {string}
     * @memberof InlineResponse200103
     * @example COIN_FUTURE
     */
    toAccountType: string;

    /**
     * @type {string}
     * @memberof InlineResponse200103
     * @example SUCCESS
     */
    status: string;

    /**
     * @type {number}
     * @memberof InlineResponse200103
     * @example 1544433325000
     */
    createTimeStamp: number;

    /**
     * @type {string}
     * @memberof InlineResponse200103
     * @example 11945860694
     */
    clientTranId: string;
}
