/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20024
 */
export interface InlineResponse20024 {

    /**
     * @type {string}
     * @memberof InlineResponse20024
     * @example BNB
     */
    base: string;

    /**
     * @type {number}
     * @memberof InlineResponse20024
     * @example 351637150141315840
     */
    id: number;

    /**
     * @type {boolean}
     * @memberof InlineResponse20024
     */
    isBuyAllowed: boolean;

    /**
     * @type {boolean}
     * @memberof InlineResponse20024
     */
    isMarginTrade: boolean;

    /**
     * @type {boolean}
     * @memberof InlineResponse20024
     */
    isSellAllowed: boolean;

    /**
     * @type {string}
     * @memberof InlineResponse20024
     * @example BTC
     */
    quote: string;

    /**
     * @type {string}
     * @memberof InlineResponse20024
     * @example BNBBTC
     */
    symbol: string;
}
