/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Sapiv1margincrossMarginCollateralRatioCollaterals } from './sapiv1margincross-margin-collateral-ratio-collaterals';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20045
 */
export interface InlineResponse20045 {

    /**
     * @type {Array<Sapiv1margincrossMarginCollateralRatioCollaterals>}
     * @memberof InlineResponse20045
     */
    collaterals: Array<Sapiv1margincrossMarginCollateralRatioCollaterals>;

    /**
     * @type {Array<string>}
     * @memberof InlineResponse20045
     */
    assetNames: Array<string>;
}
