/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse200249AssetAllocation } from './inline-response200249-asset-allocation';
 /**
 * 
 *
 * @export
 * @interface InlineResponse200249
 */
export interface InlineResponse200249 {

    /**
     * @type {number}
     * @memberof InlineResponse200249
     * @example 1
     */
    indexId: number;

    /**
     * @type {string}
     * @memberof InlineResponse200249
     * @example BINANCE TOP 10 EW
     */
    indexName: string;

    /**
     * @type {string}
     * @memberof InlineResponse200249
     * @example RUNNING
     */
    status: string;

    /**
     * @type {Array<InlineResponse200249AssetAllocation>}
     * @memberof InlineResponse200249
     */
    assetAllocation: Array<InlineResponse200249AssetAllocation>;
}
