/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20042
 */
export interface InlineResponse20042 {

    /**
     * @type {string}
     * @memberof InlineResponse20042
     * @example BTCUSDT
     */
    symbol?: string;

    /**
     * @type {number}
     * @memberof InlineResponse20042
     * @example 1
     */
    tier?: number;

    /**
     * @type {string}
     * @memberof InlineResponse20042
     * @example 10
     */
    effectiveMultiple?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20042
     * @example 1.111
     */
    initialRiskRatio?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20042
     * @example 1.05
     */
    liquidationRiskRatio?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20042
     * @example 9
     */
    baseAssetMaxBorrowable?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20042
     * @example 70000
     */
    quoteAssetMaxBorrowable?: string;
}
