/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20010OrderReports } from './inline-response20010-order-reports';
import { InlineResponse20010Orders } from './inline-response20010-orders';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20010
 */
export interface InlineResponse20010 {

    /**
     * @type {number}
     * @memberof InlineResponse20010
     * @example 0
     */
    orderListId: number;

    /**
     * @type {string}
     * @memberof InlineResponse20010
     * @example OCO
     */
    contingencyType: string;

    /**
     * @type {string}
     * @memberof InlineResponse20010
     * @example EXEC_STARTED
     */
    listStatusType: string;

    /**
     * @type {string}
     * @memberof InlineResponse20010
     * @example EXECUTING
     */
    listOrderStatus: string;

    /**
     * @type {string}
     * @memberof InlineResponse20010
     * @example JYVpp3F0f5CAG15DhtrqLp
     */
    listClientOrderId: string;

    /**
     * @type {number}
     * @memberof InlineResponse20010
     * @example 1563417480525
     */
    transactionTime: number;

    /**
     * @type {string}
     * @memberof InlineResponse20010
     * @example LTCBTC
     */
    symbol: string;

    /**
     * @type {Array<InlineResponse20010Orders>}
     * @memberof InlineResponse20010
     */
    orders: Array<InlineResponse20010Orders>;

    /**
     * @type {Array<InlineResponse20010OrderReports>}
     * @memberof InlineResponse20010
     * @example [{"symbol":"LTCBTC","orderId":2,"orderListId":0,"clientOrderId":"Kk7sqHb9J6mJWTMDVW7Vos","transactTime":1563417480525,"price":"0.000000","origQty":"0.624363","executedQty":"0.000000","cummulativeQuoteQty":"0.000000","status":"NEW","timeInForce":"GTC","type":"STOP_LOSS","side":"BUY","stopPrice":"0.960664","workingTime":-1,"selfTradePreventionMode":"NONE"},{"symbol":"LTCBTC","orderId":3,"orderListId":0,"clientOrderId":"xTXKaGYd4bluPVp78IVRvl","transactTime":1563417480525,"price":"0.036435","origQty":"0.624363","executedQty":"0.000000","cummulativeQuoteQty":"0.000000","status":"NEW","timeInForce":"GTC","type":"LIMIT_MAKER","side":"BUY","workingTime":1563417480525,"selfTradePreventionMode":"NONE"}]
     */
    orderReports: Array<InlineResponse20010OrderReports>;
}
