/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20060
 */
export interface InlineResponse20060 {

    /**
     * @type {string}
     * @memberof InlineResponse20060
     * @example 0.00999800
     */
    amount: string;

    /**
     * @type {string}
     * @memberof InlineResponse20060
     * @example PAXG
     */
    coin: string;

    /**
     * @type {string}
     * @memberof InlineResponse20060
     * @example ETH
     */
    network: string;

    /**
     * @type {number}
     * @memberof InlineResponse20060
     * @example 1
     */
    status: number;

    /**
     * @type {string}
     * @memberof InlineResponse20060
     * @example 0x788cabe9236ce061e5a892e1a59395a81fc8d62c
     */
    address: string;

    /**
     * @type {string}
     * @memberof InlineResponse20060
     */
    addressTag: string;

    /**
     * @type {string}
     * @memberof InlineResponse20060
     * @example 0xaad4654a3234aa6118af9b4b335f5ae81c360b2394721c019b5d1e75328b09f3
     */
    txId: string;

    /**
     * @type {number}
     * @memberof InlineResponse20060
     * @example 1599621997000
     */
    insertTime: number;

    /**
     * @type {number}
     * @memberof InlineResponse20060
     * @example 0
     */
    transferType: number;

    /**
     * confirm times for unlocking
     *
     * @type {string}
     * @memberof InlineResponse20060
     * @example 12/12
     */
    unlockConfirm: string;

    /**
     * @type {string}
     * @memberof InlineResponse20060
     * @example 12/12
     */
    confirmTimes: string;
}
