/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Apiv3openOrderListOrders } from './apiv3open-order-list-orders';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20013
 */
export interface InlineResponse20013 {

    /**
     * @type {number}
     * @memberof InlineResponse20013
     * @example 31
     */
    orderListId: number;

    /**
     * @type {string}
     * @memberof InlineResponse20013
     * @example OCO
     */
    contingencyType: string;

    /**
     * @type {string}
     * @memberof InlineResponse20013
     * @example EXEC_STARTED
     */
    listStatusType: string;

    /**
     * @type {string}
     * @memberof InlineResponse20013
     * @example EXECUTING
     */
    listOrderStatus: string;

    /**
     * @type {string}
     * @memberof InlineResponse20013
     * @example wuB13fmulKj3YjdqWEcsnp
     */
    listClientOrderId: string;

    /**
     * @type {number}
     * @memberof InlineResponse20013
     * @example 1565246080644
     */
    transactionTime: number;

    /**
     * @type {string}
     * @memberof InlineResponse20013
     * @example LTCBTC
     */
    symbol: string;

    /**
     * @type {Array<Apiv3openOrderListOrders>}
     * @memberof InlineResponse20013
     */
    orders: Array<Apiv3openOrderListOrders>;
}
