/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20044UserAssetDribbletDetails
 */
export interface InlineResponse20044UserAssetDribbletDetails {

    /**
     * @type {number}
     * @memberof InlineResponse20044UserAssetDribbletDetails
     * @example 4359321
     */
    transId: number;

    /**
     * @type {string}
     * @memberof InlineResponse20044UserAssetDribbletDetails
     * @example 0.000009
     */
    serviceChargeAmount: string;

    /**
     * @type {string}
     * @memberof InlineResponse20044UserAssetDribbletDetails
     * @example 0.0009
     */
    amount: string;

    /**
     * @type {number}
     * @memberof InlineResponse20044UserAssetDribbletDetails
     * @example 1615985535000
     */
    operateTime: number;

    /**
     * @type {string}
     * @memberof InlineResponse20044UserAssetDribbletDetails
     * @example 0.000441
     */
    transferedAmount: string;

    /**
     * @type {string}
     * @memberof InlineResponse20044UserAssetDribbletDetails
     * @example USDT
     */
    fromAsset: string;
}
