/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20069CTR
 */
export interface InlineResponse20069CTR {

    /**
     * @type {string}
     * @memberof InlineResponse20069CTR
     * @example 70.00000000
     */
    minWithdrawAmount: string;

    /**
     * deposit status (false if ALL of networks' are false)
     *
     * @type {boolean}
     * @memberof InlineResponse20069CTR
     * @example false
     */
    depositStatus: boolean;

    /**
     * @type {number}
     * @memberof InlineResponse20069CTR
     * @example 35
     */
    withdrawFee: number;

    /**
     * withdrawStatus status (false if ALL of networks' are false)
     *
     * @type {boolean}
     * @memberof InlineResponse20069CTR
     */
    withdrawStatus: boolean;

    /**
     * @type {string}
     * @memberof InlineResponse20069CTR
     * @example Delisted, Deposit Suspended
     */
    depositTip: string;
}
