/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200199Rows
 */
export interface InlineResponse200199Rows {

    /**
     * @type {string}
     * @memberof InlineResponse200199Rows
     * @example 12345678
     */
    loanAccountId: string;

    /**
     * @type {string}
     * @memberof InlineResponse200199Rows
     * @example 12345678
     */
    orderId: string;

    /**
     * @type {string}
     * @memberof InlineResponse200199Rows
     * @example 12345678
     */
    requestId: string;

    /**
     * @type {string}
     * @memberof InlineResponse200199Rows
     * @example BTC
     */
    loanCoin: string;

    /**
     * @type {string}
     * @memberof InlineResponse200199Rows
     * @example 100.5
     */
    loanAmount: string;

    /**
     * @type {string}
     * @memberof InlineResponse200199Rows
     * @example 12345678,12345678,12345678
     */
    collateralAccountId: string;

    /**
     * @type {string}
     * @memberof InlineResponse200199Rows
     * @example BUSD,USDT,ETH
     */
    collateralCoin: string;

    /**
     * @type {number}
     * @memberof InlineResponse200199Rows
     * @example 30
     */
    loanTerm: number;

    /**
     * @type {number}
     * @memberof InlineResponse200199Rows
     */
    status: number;
}
