/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200220Rows
 */
export interface InlineResponse200220Rows {

    /**
     * @type {string}
     * @memberof InlineResponse200220Rows
     * @example BNB
     */
    loanCoin: string;

    /**
     * @type {string}
     * @memberof InlineResponse200220Rows
     * @example BNB
     */
    collateralCoin: string;

    /**
     * @type {string}
     * @memberof InlineResponse200220Rows
     * @example ADDITIONAL
     */
    direction: string;

    /**
     * @type {string}
     * @memberof InlineResponse200220Rows
     * @example 5.75
     */
    collateralAmount: string;

    /**
     * @type {string}
     * @memberof InlineResponse200220Rows
     * @example 0.83
     */
    preLTV: string;

    /**
     * @type {string}
     * @memberof InlineResponse200220Rows
     * @example 0.5
     */
    afterLTV: string;

    /**
     * @type {number}
     * @memberof InlineResponse200220Rows
     * @example 1575018510000
     */
    adjustTime: number;
}
