/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200247Details
 */
export interface InlineResponse200247Details {

    /**
     * @type {string}
     * @memberof InlineResponse200247Details
     * @example ADA
     */
    targetAsset: string;

    /**
     * @type {string}
     * @memberof InlineResponse200247Details
     * @example 3.4
     */
    averagePriceInUSD: string;

    /**
     * @type {string}
     * @memberof InlineResponse200247Details
     * @example 222.21
     */
    totalInvestedInUSD: string;

    /**
     * @type {string}
     * @memberof InlineResponse200247Details
     * @example 122.12345678
     */
    purchasedAmount: string;

    /**
     * @type {string}
     * @memberof InlineResponse200247Details
     * @example ADA
     */
    purchasedAmountUnit: string;

    /**
     * @type {string}
     * @memberof InlineResponse200247Details
     * @example 109.2
     */
    pnlInUSD: string;

    /**
     * @type {string}
     * @memberof InlineResponse200247Details
     * @example 0.1
     */
    roi: string;

    /**
     * @type {string}
     * @memberof InlineResponse200247Details
     * @example 50
     */
    percentage: string;

    /**
     * @type {string}
     * @memberof InlineResponse200247Details
     * @example ACTIVE
     */
    assetStatus: string;

    /**
     * @type {string}
     * @memberof InlineResponse200247Details
     * @example 122.12345678
     */
    availableAmount: string;

    /**
     * @type {string}
     * @memberof InlineResponse200247Details
     * @example ADA
     */
    availableAmountUnit: string;

    /**
     * @type {string}
     * @memberof InlineResponse200247Details
     * @example 122.12345678
     */
    redeemedAmout: string;

    /**
     * @type {string}
     * @memberof InlineResponse200247Details
     * @example ADA
     */
    redeemedAmoutUnit: string;

    /**
     * @type {string}
     * @memberof InlineResponse200247Details
     * @example 101.2
     */
    assetValueInUSD: string;
}
