/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20083Transfers } from './inline-response20083-transfers';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20083
 */
export interface InlineResponse20083 {

    /**
     * @type {boolean}
     * @memberof InlineResponse20083
     */
    success: boolean;

    /**
     * @type {number}
     * @memberof InlineResponse20083
     * @example 2
     */
    futuresType: number;

    /**
     * @type {Array<InlineResponse20083Transfers>}
     * @memberof InlineResponse20083
     */
    transfers: Array<InlineResponse20083Transfers>;
}
