/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20071Rows } from './inline-response20071-rows';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20071
 */
export interface InlineResponse20071 {

    /**
     * @type {number}
     * @memberof InlineResponse20071
     * @example 1
     */
    total: number;

    /**
     * @type {Array<InlineResponse20071Rows>}
     * @memberof InlineResponse20071
     */
    rows: Array<InlineResponse20071Rows>;
}
