/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200188TotalUnclaimedRewards
 */
export interface InlineResponse200188TotalUnclaimedRewards {

    /**
     * @type {number}
     * @memberof InlineResponse200188TotalUnclaimedRewards
     * @example 100000315.79
     */
    BUSD: number;

    /**
     * @type {number}
     * @memberof InlineResponse200188TotalUnclaimedRewards
     * @example 1.0E-8
     */
    BNB: number;

    /**
     * @type {number}
     * @memberof InlineResponse200188TotalUnclaimedRewards
     * @example 2.0E-8
     */
    USDT: number;
}
