/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200137Data
 */
export interface InlineResponse200137Data {

    /**
     * @type {string}
     * @memberof InlineResponse200137Data
     * @example sha256
     */
    algoName: string;

    /**
     * @type {number}
     * @memberof InlineResponse200137Data
     * @example 1
     */
    algoId: number;

    /**
     * @type {number}
     * @memberof InlineResponse200137Data
     * @example 0
     */
    poolIndex: number;

    /**
     * @type {string}
     * @memberof InlineResponse200137Data
     * @example h/s
     */
    unit: string;
}
