/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200110
 */
export interface InlineResponse200110 {

    /**
     * @type {string}
     * @memberof InlineResponse200110
     * @example INJ
     */
    coin: string;

    /**
     * @type {string}
     * @memberof InlineResponse200110
     * @example Injective Protocol
     */
    name: string;

    /**
     * @type {string}
     * @memberof InlineResponse200110
     * @example 0
     */
    totalBalance: string;

    /**
     * @type {string}
     * @memberof InlineResponse200110
     * @example 0
     */
    availableBalance: string;

    /**
     * @type {string}
     * @memberof InlineResponse200110
     * @example 0
     */
    inOrder: string;

    /**
     * @type {string}
     * @memberof InlineResponse200110
     * @example 0
     */
    btcValue: string;
}
