/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200139HashrateDatas
 */
export interface InlineResponse200139HashrateDatas {

    /**
     * @type {number}
     * @memberof InlineResponse200139HashrateDatas
     * @example 1587902400000
     */
    time: number;

    /**
     * @type {string}
     * @memberof InlineResponse200139HashrateDatas
     * @example 0
     */
    hashrate: string;

    /**
     * Rejection Rate
     *
     * @type {number}
     * @memberof InlineResponse200139HashrateDatas
     * @example 0
     */
    reject: number;
}
