/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200127Data
 */
export interface InlineResponse200127Data {

    /**
     * @type {string}
     * @memberof InlineResponse200127Data
     * @example 353fca443f06466db0c4dc89f94f027a
     */
    orderNo: string;

    /**
     * Fiat trade amount
     *
     * @type {string}
     * @memberof InlineResponse200127Data
     * @example 20.00
     */
    sourceAmount: string;

    /**
     * Fiat token
     *
     * @type {string}
     * @memberof InlineResponse200127Data
     * @example EUR
     */
    fiatCurrency: string;

    /**
     * Crypto trade amount
     *
     * @type {string}
     * @memberof InlineResponse200127Data
     * @example 4.462
     */
    obtainAmount: string;

    /**
     * Crypto token
     *
     * @type {string}
     * @memberof InlineResponse200127Data
     * @example LUNA
     */
    cryptoCurrency: string;

    /**
     * Trade fee
     *
     * @type {string}
     * @memberof InlineResponse200127Data
     * @example 0.2
     */
    totalFee: string;

    /**
     * @type {string}
     * @memberof InlineResponse200127Data
     * @example 4.437472
     */
    price: string;

    /**
     * Processing, Completed, Failed, Refunded
     *
     * @type {string}
     * @memberof InlineResponse200127Data
     * @example Failed
     */
    status: string;

    /**
     * @type {number}
     * @memberof InlineResponse200127Data
     * @example 1624529919000
     */
    createTime: number;

    /**
     * @type {number}
     * @memberof InlineResponse200127Data
     * @example 1624529919000
     */
    updateTime: number;
}
