/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse200257Detail } from './inline-response200257-detail';
import { Sapiv1stakingproductListQuota } from './sapiv1stakingproduct-list-quota';
 /**
 * 
 *
 * @export
 * @interface InlineResponse200257Rows
 */
export interface InlineResponse200257Rows {

    /**
     * @type {string}
     * @memberof InlineResponse200257Rows
     * @example BNB
     */
    projectId: string;

    /**
     * @type {InlineResponse200257Detail}
     * @memberof InlineResponse200257Rows
     */
    detail: InlineResponse200257Detail;

    /**
     * @type {Sapiv1stakingproductListQuota}
     * @memberof InlineResponse200257Rows
     */
    quota: Sapiv1stakingproductListQuota;
}
