/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200268Rows
 */
export interface InlineResponse200268Rows {

    /**
     * @type {string}
     * @memberof InlineResponse200268Rows
     * @example BUSD
     */
    asset: string;

    /**
     * @type {string}
     * @memberof InlineResponse200268Rows
     * @example 0.00006408
     */
    rewards: string;

    /**
     * @type {string}
     * @memberof InlineResponse200268Rows
     * @example USDT001
     */
    projectId: string;

    /**
     * @type {string}
     * @memberof InlineResponse200268Rows
     * @example BONUS
     */
    type: string;

    /**
     * @type {number}
     * @memberof InlineResponse200268Rows
     * @example 1577257222000
     */
    time: number;
}
