/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse2009CancelResponse
 */
export interface InlineResponse2009CancelResponse {

    /**
     * @type {string}
     * @memberof InlineResponse2009CancelResponse
     * @example BTCUSDT
     */
    symbol: string;

    /**
     * @type {string}
     * @memberof InlineResponse2009CancelResponse
     * @example DnLo3vTAQcjha43lAZhZ0y
     */
    origClientOrderId: string;

    /**
     * @type {number}
     * @memberof InlineResponse2009CancelResponse
     * @example 9
     */
    orderId: number;

    /**
     * @type {number}
     * @memberof InlineResponse2009CancelResponse
     * @example -1
     */
    orderListId: number;

    /**
     * @type {string}
     * @memberof InlineResponse2009CancelResponse
     * @example osxN3JXAtJvKvCqGeMWMVR
     */
    clientOrderId: string;

    /**
     * @type {string}
     * @memberof InlineResponse2009CancelResponse
     * @example 0.01000000
     */
    price: string;

    /**
     * @type {string}
     * @memberof InlineResponse2009CancelResponse
     * @example 0.000100
     */
    origQty: string;

    /**
     * @type {string}
     * @memberof InlineResponse2009CancelResponse
     * @example 0.00000000
     */
    executedQty: string;

    /**
     * @type {string}
     * @memberof InlineResponse2009CancelResponse
     * @example 0.00000000
     */
    cummulativeQuoteQty: string;

    /**
     * @type {string}
     * @memberof InlineResponse2009CancelResponse
     * @example CANCELED
     */
    status: string;

    /**
     * @type {string}
     * @memberof InlineResponse2009CancelResponse
     * @example GTC
     */
    timeInForce: string;

    /**
     * @type {string}
     * @memberof InlineResponse2009CancelResponse
     * @example LIMIT
     */
    type: string;

    /**
     * @type {string}
     * @memberof InlineResponse2009CancelResponse
     * @example SELL
     */
    side: string;

    /**
     * @type {string}
     * @memberof InlineResponse2009CancelResponse
     * @example NONE
     */
    selfTradePreventionMode: string;

    /**
     * @type {number}
     * @memberof InlineResponse2009CancelResponse
     * @example 1507725176595
     */
    transactTime?: number;
}
