/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Sapiv1marginisolatedMarginDataData } from './sapiv1marginisolated-margin-data-data';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20041
 */
export interface InlineResponse20041 {

    /**
     * @type {number}
     * @memberof InlineResponse20041
     * @example 0
     */
    vipLevel?: number;

    /**
     * @type {string}
     * @memberof InlineResponse20041
     * @example BTCUSDT
     */
    symbol?: string;

    /**
     * @type {string}
     * @memberof InlineResponse20041
     * @example 10
     */
    leverage?: string;

    /**
     * @type {Array<Sapiv1marginisolatedMarginDataData>}
     * @memberof InlineResponse20041
     * @example [{"coin":"BTC","dailyInterest":"0.00026125","borrowLimit":"270"},{"coin":"USDT","dailyInterest":"0.000475","borrowLimit":"2100000"}]
     */
    data?: Array<Sapiv1marginisolatedMarginDataData>;
}
