/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200212
 */
export interface InlineResponse200212 {

    /**
     * @type {string}
     * @memberof InlineResponse200212
     * @example BUSD
     */
    loanCoin: string;

    /**
     * @type {string}
     * @memberof InlineResponse200212
     * @example BUSD
     */
    collateralCoin: string;

    /**
     * @type {string}
     * @memberof InlineResponse200212
     * @example 1000
     */
    repayAmount: string;

    /**
     * rate of collateral coin/loan coin
     *
     * @type {string}
     * @memberof InlineResponse200212
     * @example 300.36781234
     */
    rate: string;
}
