/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse200237Data } from './inline-response200237-data';
 /**
 * 
 *
 * @export
 * @interface InlineResponse200237
 */
export interface InlineResponse200237 {

    /**
     * @type {string}
     * @memberof InlineResponse200237
     * @example 000000
     */
    code: string;

    /**
     * @type {string}
     * @memberof InlineResponse200237
     * @example success
     */
    message: string;

    /**
     * @type {InlineResponse200237Data}
     * @memberof InlineResponse200237
     */
    data: InlineResponse200237Data;

    /**
     * @type {boolean}
     * @memberof InlineResponse200237
     */
    success: boolean;
}
