/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200102
 */
export interface InlineResponse200102 {

    /**
     * @type {string}
     * @memberof InlineResponse200102
     * @example master
     */
    counterParty: string;

    /**
     * @type {string}
     * @memberof InlineResponse200102
     * @example master@test.com
     */
    email: string;

    /**
     * 1 for transfer in, 2 for transfer out
     *
     * @type {number}
     * @memberof InlineResponse200102
     * @example 1
     */
    type: number;

    /**
     * @type {string}
     * @memberof InlineResponse200102
     * @example BTC
     */
    asset: string;

    /**
     * @type {string}
     * @memberof InlineResponse200102
     * @example 1
     */
    qty: string;

    /**
     * @type {string}
     * @memberof InlineResponse200102
     * @example SPOT
     */
    fromAccountType: string;

    /**
     * @type {string}
     * @memberof InlineResponse200102
     * @example SPOT
     */
    toAccountType: string;

    /**
     * @type {string}
     * @memberof InlineResponse200102
     * @example SUCCESS
     */
    status: string;

    /**
     * @type {number}
     * @memberof InlineResponse200102
     * @example 11798835829
     */
    tranId: number;

    /**
     * @type {number}
     * @memberof InlineResponse200102
     * @example 1544433325000
     */
    time: number;
}
