/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20096SubAccountList } from './inline-response20096-sub-account-list';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20096
 */
export interface InlineResponse20096 {

    /**
     * @type {string}
     * @memberof InlineResponse20096
     * @example 4.33333333
     */
    totalAssetOfBtc: string;

    /**
     * @type {string}
     * @memberof InlineResponse20096
     * @example 2.11111112
     */
    totalLiabilityOfBtc: string;

    /**
     * @type {string}
     * @memberof InlineResponse20096
     * @example 2.22222221
     */
    totalNetAssetOfBtc: string;

    /**
     * @type {Array<InlineResponse20096SubAccountList>}
     * @memberof InlineResponse20096
     */
    subAccountList: Array<InlineResponse20096SubAccountList>;
}
