/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200228
 */
export interface InlineResponse200228 {

    /**
     * @type {number}
     * @memberof InlineResponse200228
     * @example 933256278426274400
     */
    orderId: number;

    /**
     * @type {string}
     * @memberof InlineResponse200228
     * @example SUCCESS
     */
    orderStatus: string;

    /**
     * @type {string}
     * @memberof InlineResponse200228
     * @example BTC
     */
    fromAsset: string;

    /**
     * @type {string}
     * @memberof InlineResponse200228
     * @example 0.00054414
     */
    fromAmount: string;

    /**
     * @type {string}
     * @memberof InlineResponse200228
     * @example USDT
     */
    toAsset: string;

    /**
     * @type {string}
     * @memberof InlineResponse200228
     * @example 20
     */
    toAmount: string;

    /**
     * @type {string}
     * @memberof InlineResponse200228
     * @example 36755
     */
    ratio: string;

    /**
     * @type {string}
     * @memberof InlineResponse200228
     * @example 0.00002721
     */
    inverseRatio: string;

    /**
     * @type {number}
     * @memberof InlineResponse200228
     * @example 1623381330472
     */
    createTime: number;
}
