/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse200120TradeInfoVos } from './inline-response200120-trade-info-vos';
 /**
 * 
 *
 * @export
 * @interface InlineResponse200120
 */
export interface InlineResponse200120 {

    /**
     * @type {string}
     * @memberof InlineResponse200120
     * @example 0
     */
    recent30BtcTotal: string;

    /**
     * @type {string}
     * @memberof InlineResponse200120
     * @example 0
     */
    recent30BtcFuturesTotal: string;

    /**
     * @type {string}
     * @memberof InlineResponse200120
     * @example 0
     */
    recent30BtcMarginTotal: string;

    /**
     * @type {string}
     * @memberof InlineResponse200120
     * @example 0
     */
    recent30BusdTotal: string;

    /**
     * @type {string}
     * @memberof InlineResponse200120
     * @example 0
     */
    recent30BusdFuturesTotal: string;

    /**
     * @type {string}
     * @memberof InlineResponse200120
     * @example 0
     */
    recent30BusdMarginTotal: string;

    /**
     * @type {Array<InlineResponse200120TradeInfoVos>}
     * @memberof InlineResponse200120
     */
    tradeInfoVos: Array<InlineResponse200120TradeInfoVos>;
}
