/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200271
 */
export interface InlineResponse200271 {

    /**
     * @type {string}
     * @memberof InlineResponse200271
     * @example AXS
     */
    rewardAsset: string;

    /**
     * @type {string}
     * @memberof InlineResponse200271
     * @example 5.17181528
     */
    totalRewardAmt: string;

    /**
     * @type {string}
     * @memberof InlineResponse200271
     * @example BNB
     */
    extraRewardAsset: string;

    /**
     * @type {string}
     * @memberof InlineResponse200271
     * @example 5.17181528
     */
    estTotalExtraRewardAmt: string;

    /**
     * @type {string}
     * @memberof InlineResponse200271
     * @example 1.29295383
     */
    nextPay: string;

    /**
     * @type {string}
     * @memberof InlineResponse200271
     * @example 1646697600000
     */
    nextPayDate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200271
     * @example 1646697600000
     */
    valueDate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200271
     * @example 1651449600000
     */
    rewardsEndDate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200271
     * @example 1651536000000
     */
    deliverDate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200271
     * @example 1651536000000
     */
    nextSubscriptionDate: string;
}
