/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20051Assets
 */
export interface InlineResponse20051Assets {

    /**
     * @type {string}
     * @memberof InlineResponse20051Assets
     * @example 100000000
     */
    MATIC: string;

    /**
     * @type {string}
     * @memberof InlineResponse20051Assets
     * @example 100000000
     */
    STPT: string;

    /**
     * @type {string}
     * @memberof InlineResponse20051Assets
     * @example 100000000
     */
    TVK: string;

    /**
     * @type {string}
     * @memberof InlineResponse20051Assets
     * @example 97409653
     */
    SHIB: string;
}
