/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20062
 */
export interface InlineResponse20062 {

    /**
     * @type {string}
     * @memberof InlineResponse20062
     * @example 1HPn8Rx2y6nNSfagQBKy27GB99Vbzg89wv
     */
    address: string;

    /**
     * @type {string}
     * @memberof InlineResponse20062
     * @example BTC
     */
    coin: string;

    /**
     * @type {string}
     * @memberof InlineResponse20062
     */
    tag: string;

    /**
     * @type {string}
     * @memberof InlineResponse20062
     * @example https://btc.com/1HPn8Rx2y6nNSfagQBKy27GB99Vbzg89wv
     */
    url: string;
}
