/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse2001Filters
 */
export interface InlineResponse2001Filters {

    /**
     * @type {string}
     * @memberof InlineResponse2001Filters
     * @example PRICE_FILTER
     */
    filterType: string;

    /**
     * @type {string}
     * @memberof InlineResponse2001Filters
     * @example 0.00000100
     */
    minPrice: string;

    /**
     * @type {string}
     * @memberof InlineResponse2001Filters
     * @example 100000.00000000
     */
    maxPrice: string;

    /**
     * @type {string}
     * @memberof InlineResponse2001Filters
     * @example 0.00000100
     */
    tickSize: string;
}
