/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20043
 */
export interface InlineResponse20043 {

    /**
     * @type {string}
     * @memberof InlineResponse20043
     * @example ORDERS
     */
    rateLimitType: string;

    /**
     * @type {string}
     * @memberof InlineResponse20043
     * @example SECOND
     */
    interval: string;

    /**
     * @type {number}
     * @memberof InlineResponse20043
     * @example 10
     */
    intervalNum: number;

    /**
     * @type {number}
     * @memberof InlineResponse20043
     * @example 10000
     */
    limit: number;

    /**
     * @type {number}
     * @memberof InlineResponse20043
     * @example 0
     */
    count: number;
}
