/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20035
 */
export interface InlineResponse20035 {

    /**
     * Account's currently max borrowable amount with sufficient system availability
     *
     * @type {string}
     * @memberof InlineResponse20035
     * @example 1.5
     */
    normalBar?: string;

    /**
     * Max borrowable amount limited by the account level
     *
     * @type {string}
     * @memberof InlineResponse20035
     * @example 1.3
     */
    marginCallBar?: string;

    /**
     * Liquidation Margin Ratio
     *
     * @type {string}
     * @memberof InlineResponse20035
     * @example 1.1
     */
    forceLiquidationBar?: string;
}
