/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200113DataPosition
 */
export interface InlineResponse200113DataPosition {

    /**
     * @type {string}
     * @memberof InlineResponse200113DataPosition
     * @example BTCUSDT
     */
    symbol: string;

    /**
     * @type {number}
     * @memberof InlineResponse200113DataPosition
     * @example 17000
     */
    entryPrice: number;

    /**
     * @type {number}
     * @memberof InlineResponse200113DataPosition
     * @example 17000
     */
    markPrice: number;

    /**
     * @type {number}
     * @memberof InlineResponse200113DataPosition
     * @example 0.1
     */
    positionAmt: number;
}
