/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse200256TierAnnualPercentageRate } from './inline-response200256-tier-annual-percentage-rate';
 /**
 * 
 *
 * @export
 * @interface InlineResponse200261Rows
 */
export interface InlineResponse200261Rows {

    /**
     * @type {string}
     * @memberof InlineResponse200261Rows
     * @example 75.46000000
     */
    totalAmount: string;

    /**
     * @type {InlineResponse200256TierAnnualPercentageRate}
     * @memberof InlineResponse200261Rows
     */
    tierAnnualPercentageRate: InlineResponse200256TierAnnualPercentageRate;

    /**
     * @type {string}
     * @memberof InlineResponse200261Rows
     * @example 0.02599895
     */
    latestAnnualPercentageRate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200261Rows
     * @example 0.02599895
     */
    yesterdayAirdropPercentageRate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200261Rows
     * @example USDT
     */
    asset: string;

    /**
     * @type {string}
     * @memberof InlineResponse200261Rows
     * @example BETH
     */
    airDropAsset: string;

    /**
     * @type {boolean}
     * @memberof InlineResponse200261Rows
     * @example true
     */
    canRedeem: boolean;

    /**
     * @type {string}
     * @memberof InlineResponse200261Rows
     * @example 232.23123213
     */
    collateralAmount: string;

    /**
     * @type {string}
     * @memberof InlineResponse200261Rows
     * @example USDT001
     */
    productId: string;

    /**
     * @type {string}
     * @memberof InlineResponse200261Rows
     * @example 0.10293829
     */
    yesterdayRealTimeRewards: string;

    /**
     * @type {string}
     * @memberof InlineResponse200261Rows
     * @example 0.22759183
     */
    cumulativeBonusRewards: string;

    /**
     * @type {string}
     * @memberof InlineResponse200261Rows
     * @example 0.22759183
     */
    cumulativeRealTimeRewards: string;

    /**
     * @type {string}
     * @memberof InlineResponse200261Rows
     * @example 0.45459183
     */
    cumulativeTotalRewards: string;

    /**
     * @type {boolean}
     * @memberof InlineResponse200261Rows
     * @example true
     */
    autoSubscribe: boolean;
}
