/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200144DataProfitTransferDetails
 */
export interface InlineResponse200144DataProfitTransferDetails {

    /**
     * Transfer out of sub-account
     *
     * @type {string}
     * @memberof InlineResponse200144DataProfitTransferDetails
     * @example test4001
     */
    poolUsername: string;

    /**
     * Transfer into subaccount
     *
     * @type {string}
     * @memberof InlineResponse200144DataProfitTransferDetails
     * @example pop
     */
    toPoolUsername: string;

    /**
     * Transfer algorithm
     *
     * @type {string}
     * @memberof InlineResponse200144DataProfitTransferDetails
     * @example sha256
     */
    algoName: string;

    /**
     * Transferred Hashrate quantity
     *
     * @type {number}
     * @memberof InlineResponse200144DataProfitTransferDetails
     * @example 200000000000
     */
    hashRate: number;

    /**
     * Transfer date
     *
     * @type {number}
     * @memberof InlineResponse200144DataProfitTransferDetails
     * @example 20201213
     */
    day: number;

    /**
     * Transfer income
     *
     * @type {number}
     * @memberof InlineResponse200144DataProfitTransferDetails
     * @example 0.2256872
     */
    amount: number;

    /**
     * @type {string}
     * @memberof InlineResponse200144DataProfitTransferDetails
     * @example BTC
     */
    coinName: string;
}
