/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Apiv3allOrderListOrders } from './apiv3all-order-list-orders';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20012
 */
export interface InlineResponse20012 {

    /**
     * @type {number}
     * @memberof InlineResponse20012
     * @example 29
     */
    orderListId: number;

    /**
     * @type {string}
     * @memberof InlineResponse20012
     * @example OCO
     */
    contingencyType: string;

    /**
     * @type {string}
     * @memberof InlineResponse20012
     * @example EXEC_STARTED
     */
    listStatusType: string;

    /**
     * @type {string}
     * @memberof InlineResponse20012
     * @example EXECUTING
     */
    listOrderStatus: string;

    /**
     * @type {string}
     * @memberof InlineResponse20012
     * @example amEEAXryFzFwYF1FeRpUoZ
     */
    listClientOrderId: string;

    /**
     * @type {number}
     * @memberof InlineResponse20012
     * @example 1565245913483
     */
    transactionTime: number;

    /**
     * @type {string}
     * @memberof InlineResponse20012
     * @example LTCBTC
     */
    symbol: string;

    /**
     * @type {boolean}
     * @memberof InlineResponse20012
     */
    isIsolated: boolean;

    /**
     * @type {Array<Apiv3allOrderListOrders>}
     * @memberof InlineResponse20012
     */
    orders: Array<Apiv3allOrderListOrders>;
}
