/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse2009NewOrderResponse
 */
export interface InlineResponse2009NewOrderResponse {

    /**
     * @type {string}
     * @memberof InlineResponse2009NewOrderResponse
     * @example BTCUSDT
     */
    symbol: string;

    /**
     * @type {number}
     * @memberof InlineResponse2009NewOrderResponse
     * @example 10
     */
    orderId: number;

    /**
     * @type {number}
     * @memberof InlineResponse2009NewOrderResponse
     * @example -1
     */
    orderListId: number;

    /**
     * @type {string}
     * @memberof InlineResponse2009NewOrderResponse
     * @example wOceeeOzNORyLiQfw7jd8S
     */
    clientOrderId: string;

    /**
     * @type {number}
     * @memberof InlineResponse2009NewOrderResponse
     * @example 1652928801803
     */
    transactTime: number;

    /**
     * @type {string}
     * @memberof InlineResponse2009NewOrderResponse
     * @example 0.02000000
     */
    price: string;

    /**
     * @type {string}
     * @memberof InlineResponse2009NewOrderResponse
     * @example 0.040000
     */
    origQty: string;

    /**
     * @type {string}
     * @memberof InlineResponse2009NewOrderResponse
     * @example 0.00000000
     */
    executedQty: string;

    /**
     * @type {string}
     * @memberof InlineResponse2009NewOrderResponse
     * @example 0.00000000
     */
    cummulativeQuoteQty: string;

    /**
     * @type {string}
     * @memberof InlineResponse2009NewOrderResponse
     * @example NEW
     */
    status: string;

    /**
     * @type {string}
     * @memberof InlineResponse2009NewOrderResponse
     * @example GTC
     */
    timeInForce: string;

    /**
     * @type {string}
     * @memberof InlineResponse2009NewOrderResponse
     * @example LIMIT
     */
    type: string;

    /**
     * @type {string}
     * @memberof InlineResponse2009NewOrderResponse
     * @example BUY
     */
    side: string;

    /**
     * @type {number}
     * @memberof InlineResponse2009NewOrderResponse
     * @example 1669277163808
     */
    workingTime: number;

    /**
     * @type {Array<string>}
     * @memberof InlineResponse2009NewOrderResponse
     */
    fills: Array<string>;

    /**
     * @type {string}
     * @memberof InlineResponse2009NewOrderResponse
     * @example NONE
     */
    selfTradePreventionMode: string;
}
