/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200153
 */
export interface InlineResponse200153 {

    /**
     * @type {string}
     * @memberof InlineResponse200153
     * @example 00358ce6a268403398bd34eaa36dffe7
     */
    clientAlgoId: string;

    /**
     * @type {boolean}
     * @memberof InlineResponse200153
     * @example true
     */
    success: boolean;

    /**
     * @type {number}
     * @memberof InlineResponse200153
     * @example 0
     */
    code: number;

    /**
     * @type {string}
     * @memberof InlineResponse200153
     * @example OK
     */
    msg: string;
}
