/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Sapiv1marginleverageBracketBrackets } from './sapiv1marginleverage-bracket-brackets';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20055
 */
export interface InlineResponse20055 {

    /**
     * @type {Array<string>}
     * @memberof InlineResponse20055
     */
    assetNames: Array<string>;

    /**
     * @type {number}
     * @memberof InlineResponse20055
     * @example 1
     */
    rank: number;

    /**
     * @type {Array<Sapiv1marginleverageBracketBrackets>}
     * @memberof InlineResponse20055
     */
    brackets: Array<Sapiv1marginleverageBracketBrackets>;
}
