/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20014Fills } from './inline-response20014-fills';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20014
 */
export interface InlineResponse20014 {

    /**
     * @type {string}
     * @memberof InlineResponse20014
     * @example BTCUSDT
     */
    symbol: string;

    /**
     * @type {number}
     * @memberof InlineResponse20014
     * @example 2
     */
    orderId: number;

    /**
     * @type {number}
     * @memberof InlineResponse20014
     * @example -1
     */
    orderListId: number;

    /**
     * @type {string}
     * @memberof InlineResponse20014
     * @example sBI1KM6nNtOfj5tccZSKly
     */
    clientOrderId: string;

    /**
     * @type {number}
     * @memberof InlineResponse20014
     * @example 1689149087774
     */
    transactTime: number;

    /**
     * @type {string}
     * @memberof InlineResponse20014
     * @example 31000.00000000
     */
    price: string;

    /**
     * @type {string}
     * @memberof InlineResponse20014
     * @example 0.50000000
     */
    origQty: string;

    /**
     * @type {string}
     * @memberof InlineResponse20014
     * @example 0.50000000
     */
    executedQty: string;

    /**
     * @type {string}
     * @memberof InlineResponse20014
     * @example 14000.00000000
     */
    cummulativeQuoteQty: string;

    /**
     * @type {string}
     * @memberof InlineResponse20014
     * @example FILLED
     */
    status: string;

    /**
     * @type {string}
     * @memberof InlineResponse20014
     * @example GTC
     */
    timeInForce: string;

    /**
     * @type {string}
     * @memberof InlineResponse20014
     * @example LIMIT
     */
    type: string;

    /**
     * @type {string}
     * @memberof InlineResponse20014
     * @example BUY
     */
    side: string;

    /**
     * @type {number}
     * @memberof InlineResponse20014
     * @example 1689149087774
     */
    workingTime: number;

    /**
     * @type {Array<InlineResponse20014Fills>}
     * @memberof InlineResponse20014
     */
    fills: Array<InlineResponse20014Fills>;

    /**
     * @type {string}
     * @memberof InlineResponse20014
     * @example SOR
     */
    workingFloor: string;

    /**
     * @type {string}
     * @memberof InlineResponse20014
     * @example NONE
     */
    selfTradePreventionMode: string;

    /**
     * @type {boolean}
     * @memberof InlineResponse20014
     * @example true
     */
    usedSor: boolean;
}
