/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20028Rows
 */
export interface InlineResponse20028Rows {

    /**
     * @type {string}
     * @memberof InlineResponse20028Rows
     */
    avgPrice: string;

    /**
     * @type {string}
     * @memberof InlineResponse20028Rows
     */
    executedQty: string;

    /**
     * @type {number}
     * @memberof InlineResponse20028Rows
     */
    orderId: number;

    /**
     * @type {string}
     * @memberof InlineResponse20028Rows
     */
    price: string;

    /**
     * @type {string}
     * @memberof InlineResponse20028Rows
     */
    qty: string;

    /**
     * @type {string}
     * @memberof InlineResponse20028Rows
     */
    side: string;

    /**
     * @type {string}
     * @memberof InlineResponse20028Rows
     */
    symbol: string;

    /**
     * @type {string}
     * @memberof InlineResponse20028Rows
     */
    timeInForce: string;

    /**
     * @type {boolean}
     * @memberof InlineResponse20028Rows
     */
    isIsolated: boolean;

    /**
     * @type {number}
     * @memberof InlineResponse20028Rows
     */
    updatedTime: number;
}
