/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200262Rows
 */
export interface InlineResponse200262Rows {

    /**
     * @type {string}
     * @memberof InlineResponse200262Rows
     * @example 123123
     */
    positionId: string;

    /**
     * @type {string}
     * @memberof InlineResponse200262Rows
     * @example Axs*90
     */
    projectId: string;

    /**
     * @type {string}
     * @memberof InlineResponse200262Rows
     * @example AXS
     */
    asset: string;

    /**
     * @type {string}
     * @memberof InlineResponse200262Rows
     * @example 122.09202928
     */
    amount: string;

    /**
     * @type {string}
     * @memberof InlineResponse200262Rows
     * @example 1646182276000
     */
    purchaseTime: string;

    /**
     * @type {string}
     * @memberof InlineResponse200262Rows
     * @example 60
     */
    duration: string;

    /**
     * @type {string}
     * @memberof InlineResponse200262Rows
     * @example 4
     */
    accrualDays: string;

    /**
     * @type {string}
     * @memberof InlineResponse200262Rows
     * @example AXS
     */
    rewardAsset: string;

    /**
     * @type {string}
     * @memberof InlineResponse200262Rows
     * @example 0.23
     */
    APY: string;

    /**
     * @type {boolean}
     * @memberof InlineResponse200262Rows
     * @example true
     */
    isRenewable: boolean;

    /**
     * @type {boolean}
     * @memberof InlineResponse200262Rows
     * @example true
     */
    isAutoRenew: boolean;

    /**
     * @type {string}
     * @memberof InlineResponse200262Rows
     * @example 1732182276000
     */
    redeemDate: string;
}
