/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20029UserAssets
 */
export interface InlineResponse20029UserAssets {

    /**
     * @type {string}
     * @memberof InlineResponse20029UserAssets
     * @example BTC
     */
    asset: string;

    /**
     * @type {string}
     * @memberof InlineResponse20029UserAssets
     * @example 0.00000000
     */
    borrowed: string;

    /**
     * @type {string}
     * @memberof InlineResponse20029UserAssets
     * @example 0.00499500
     */
    free: string;

    /**
     * @type {string}
     * @memberof InlineResponse20029UserAssets
     * @example 0.00000000
     */
    interest: string;

    /**
     * @type {string}
     * @memberof InlineResponse20029UserAssets
     * @example 0.00000000
     */
    locked: string;

    /**
     * @type {string}
     * @memberof InlineResponse20029UserAssets
     * @example 0.00499500
     */
    netAsset: string;
}
