/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200208
 */
export interface InlineResponse200208 {

    /**
     * @type {string}
     * @memberof InlineResponse200208
     * @example BUSD
     */
    loanCoin: string;

    /**
     * @type {string}
     * @memberof InlineResponse200208
     * @example BNB
     */
    collateralCoin: string;

    /**
     * @type {string}
     * @memberof InlineResponse200208
     * @example ADDITIONAL
     */
    direction: string;

    /**
     * @type {string}
     * @memberof InlineResponse200208
     * @example 5.235
     */
    amount: string;

    /**
     * @type {string}
     * @memberof InlineResponse200208
     * @example 0.52
     */
    currentLTV: string;
}
