/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20081SubAccounts
 */
export interface InlineResponse20081SubAccounts {

    /**
     * @type {string}
     * @memberof InlineResponse20081SubAccounts
     * @example testsub@gmail.com
     */
    email: string;

    /**
     * @type {boolean}
     * @memberof InlineResponse20081SubAccounts
     * @example false
     */
    isFreeze: boolean;

    /**
     * @type {number}
     * @memberof InlineResponse20081SubAccounts
     * @example 1544433328000
     */
    createTime: number;

    /**
     * @type {boolean}
     * @memberof InlineResponse20081SubAccounts
     * @example false
     */
    isManagedSubAccount: boolean;

    /**
     * @type {boolean}
     * @memberof InlineResponse20081SubAccounts
     * @example false
     */
    isAssetManagementSubAccount: boolean;
}
