/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200198Rows
 */
export interface InlineResponse200198Rows {

    /**
     * @type {string}
     * @memberof InlineResponse200198Rows
     * @example BUSD
     */
    collateralCoin: string;

    /**
     * @type {string}
     * @memberof InlineResponse200198Rows
     * @example 100%
     */
    _1stCollateralRatio: string;

    /**
     * @type {string}
     * @memberof InlineResponse200198Rows
     * @example 1-10000000
     */
    _1stCollateralRange: string;

    /**
     * @type {string}
     * @memberof InlineResponse200198Rows
     * @example 80%
     */
    _2ndCollateralRatio: string;

    /**
     * @type {string}
     * @memberof InlineResponse200198Rows
     * @example 10000000-100000000
     */
    _2ndCollateralRange: string;

    /**
     * @type {string}
     * @memberof InlineResponse200198Rows
     * @example 60%
     */
    _3rdCollateralRatio: string;

    /**
     * @type {string}
     * @memberof InlineResponse200198Rows
     * @example 100000000-1000000000
     */
    _3rdCollateralRange: string;

    /**
     * @type {string}
     * @memberof InlineResponse200198Rows
     * @example 0%
     */
    _4thCollateralRatio: string;

    /**
     * @type {string}
     * @memberof InlineResponse200198Rows
     * @example >10000000000
     */
    _4thCollateralRange: string;
}
