/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200194Rows
 */
export interface InlineResponse200194Rows {

    /**
     * @type {string}
     * @memberof InlineResponse200194Rows
     * @example BUSD
     */
    loanCoin: string;

    /**
     * @type {string}
     * @memberof InlineResponse200194Rows
     * @example 10000
     */
    repayAmount: string;

    /**
     * @type {string}
     * @memberof InlineResponse200194Rows
     * @example BNB,BTC,ETH
     */
    collateralCoin: string;

    /**
     * Repaid, Repaying, Failed
     *
     * @type {string}
     * @memberof InlineResponse200194Rows
     * @example Repaid
     */
    repayStatus: string;

    /**
     * @type {string}
     * @memberof InlineResponse200194Rows
     * @example 1575018510000
     */
    repayTime: string;

    /**
     * @type {string}
     * @memberof InlineResponse200194Rows
     * @example 756783308056935434
     */
    orderId: string;
}
