/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200100
 */
export interface InlineResponse200100 {

    /**
     * @type {string}
     * @memberof InlineResponse200100
     * @example 9975.12000
     */
    entryPrice: string;

    /**
     * current initial leverage
     *
     * @type {string}
     * @memberof InlineResponse200100
     * @example 50
     */
    leverage: string;

    /**
     * notional value limit of current initial leverage
     *
     * @type {string}
     * @memberof InlineResponse200100
     * @example 1000000
     */
    maxNotional: string;

    /**
     * @type {string}
     * @memberof InlineResponse200100
     * @example 7963.54
     */
    liquidationPrice: string;

    /**
     * @type {string}
     * @memberof InlineResponse200100
     * @example 9973.50770517
     */
    markPrice: string;

    /**
     * @type {string}
     * @memberof InlineResponse200100
     * @example 0.010
     */
    positionAmount: string;

    /**
     * @type {string}
     * @memberof InlineResponse200100
     * @example BTCUSDT
     */
    symbol: string;

    /**
     * @type {string}
     * @memberof InlineResponse200100
     * @example -0.01612295
     */
    unrealizedProfit: string;
}
