/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20016
 */
export interface InlineResponse20016 {

    /**
     * @type {string}
     * @memberof InlineResponse20016
     * @example BTCUSDT
     */
    symbol: string;

    /**
     * @type {number}
     * @memberof InlineResponse20016
     * @example 1
     */
    preventedMatchId: number;

    /**
     * @type {number}
     * @memberof InlineResponse20016
     * @example 5
     */
    takerOrderId: number;

    /**
     * @type {number}
     * @memberof InlineResponse20016
     * @example 3
     */
    makerOrderId: number;

    /**
     * @type {number}
     * @memberof InlineResponse20016
     * @example 1
     */
    tradeGroupId: number;

    /**
     * @type {string}
     * @memberof InlineResponse20016
     * @example EXPIRE_MAKER
     */
    selfTradePreventionMode: string;

    /**
     * @type {string}
     * @memberof InlineResponse20016
     * @example 1.100000
     */
    price: string;

    /**
     * @type {string}
     * @memberof InlineResponse20016
     * @example 1.300000
     */
    makerPreventedQuantity: string;

    /**
     * @type {number}
     * @memberof InlineResponse20016
     * @example 1669101687094
     */
    transactTime: number;
}
