/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200236Data
 */
export interface InlineResponse200236Data {

    /**
     * @type {string}
     * @memberof InlineResponse200236Data
     * @example BNB
     */
    token: string;

    /**
     * @type {string}
     * @memberof InlineResponse200236Data
     * @example 10
     */
    amount: string;

    /**
     * @type {string}
     * @memberof InlineResponse200236Data
     * @example 0033002327977405
     */
    referenceNo: string;

    /**
     * @type {string}
     * @memberof InlineResponse200236Data
     * @example 10316281761814589440
     */
    identityNo: string;
}
