/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200229List
 */
export interface InlineResponse200229List {

    /**
     * @type {string}
     * @memberof InlineResponse200229List
     * @example f3b91c525b2644c7bc1e1cd31b6e1aa6
     */
    quoteId: string;

    /**
     * @type {number}
     * @memberof InlineResponse200229List
     * @example 940708407462087200
     */
    orderId: number;

    /**
     * @type {string}
     * @memberof InlineResponse200229List
     * @example SUCCESS
     */
    orderStatus: string;

    /**
     * @type {string}
     * @memberof InlineResponse200229List
     * @example USDT
     */
    fromAsset: string;

    /**
     * @type {string}
     * @memberof InlineResponse200229List
     * @example 20
     */
    fromAmount: string;

    /**
     * @type {string}
     * @memberof InlineResponse200229List
     * @example BNB
     */
    toAsset: string;

    /**
     * @type {string}
     * @memberof InlineResponse200229List
     * @example 0.06154036
     */
    toAmount: string;

    /**
     * price ratio
     *
     * @type {string}
     * @memberof InlineResponse200229List
     * @example 0.00307702
     */
    ratio: string;

    /**
     * inverse price
     *
     * @type {string}
     * @memberof InlineResponse200229List
     * @example 324.99
     */
    inverseRatio: string;

    /**
     * @type {number}
     * @memberof InlineResponse200229List
     * @example 1624248872184
     */
    createTime: number;
}
