/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse200142DataOtherProfits } from './inline-response200142-data-other-profits';
 /**
 * 
 *
 * @export
 * @interface InlineResponse200142Data
 */
export interface InlineResponse200142Data {

    /**
     * @type {Array<InlineResponse200142DataOtherProfits>}
     * @memberof InlineResponse200142Data
     */
    otherProfits: Array<InlineResponse200142DataOtherProfits>;

    /**
     * Total Rows
     *
     * @type {number}
     * @memberof InlineResponse200142Data
     * @example 3
     */
    totalNum: number;

    /**
     * Rows per page
     *
     * @type {number}
     * @memberof InlineResponse200142Data
     * @example 20
     */
    pageSize: number;
}
