/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse20081SubAccounts } from './inline-response20081-sub-accounts';
 /**
 * 
 *
 * @export
 * @interface InlineResponse20081
 */
export interface InlineResponse20081 {

    /**
     * @type {Array<InlineResponse20081SubAccounts>}
     * @memberof InlineResponse20081
     */
    subAccounts: Array<InlineResponse20081SubAccounts>;
}
