/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse200250AssetAllocation } from './inline-response200250-asset-allocation';
import { InlineResponse200250Details } from './inline-response200250-details';
 /**
 * 
 *
 * @export
 * @interface InlineResponse200250
 */
export interface InlineResponse200250 {

    /**
     * @type {number}
     * @memberof InlineResponse200250
     * @example 1
     */
    indexId: number;

    /**
     * @type {string}
     * @memberof InlineResponse200250
     * @example 114.555
     */
    totalInvestedInUSD: string;

    /**
     * current invest
     *
     * @type {string}
     * @memberof InlineResponse200250
     * @example 101.2
     */
    currentInvestedInUSD: string;

    /**
     * PNL of the plan in USD based on current amount
     *
     * @type {string}
     * @memberof InlineResponse200250
     * @example 101.2
     */
    pnlInUSD: string;

    /**
     * ROI of the plan based on current amount
     *
     * @type {string}
     * @memberof InlineResponse200250
     * @example 1.023
     */
    roi: string;

    /**
     * @type {Array<InlineResponse200250AssetAllocation>}
     * @memberof InlineResponse200250
     */
    assetAllocation: Array<InlineResponse200250AssetAllocation>;

    /**
     * @type {Array<InlineResponse200250Details>}
     * @memberof InlineResponse200250
     */
    details: Array<InlineResponse200250Details>;
}
