/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20093
 */
export interface InlineResponse20093 {

    /**
     * @type {string}
     * @memberof InlineResponse20093
     * @example 123@test.com
     */
    email: string;

    /**
     * @type {boolean}
     * @memberof InlineResponse20093
     */
    isSubUserEnabled: boolean;

    /**
     * @type {boolean}
     * @memberof InlineResponse20093
     */
    isUserActive: boolean;

    /**
     * sub account create time
     *
     * @type {number}
     * @memberof InlineResponse20093
     * @example 1570791523523
     */
    insertTime: number;

    /**
     * @type {boolean}
     * @memberof InlineResponse20093
     */
    isMarginEnabled: boolean;

    /**
     * @type {boolean}
     * @memberof InlineResponse20093
     */
    isFutureEnabled: boolean;

    /**
     * user mobile number
     *
     * @type {number}
     * @memberof InlineResponse20093
     * @example 1570791523523
     */
    mobile: number;
}
