/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200178
 */
export interface InlineResponse200178 {

    /**
     * @type {number}
     * @memberof InlineResponse200178
     * @example 2
     */
    poolId: number;

    /**
     * @type {string}
     * @memberof InlineResponse200178
     * @example BUSD/USDT
     */
    poolName: string;

    /**
     * @type {Array<string>}
     * @memberof InlineResponse200178
     * @example ["BUSD","USDT"]
     */
    assets: Array<string>;
}
