/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Sapiv1stakingproductListDetail } from './sapiv1stakingproduct-list-detail';
import { Sapiv1stakingproductListQuota } from './sapiv1stakingproduct-list-quota';
 /**
 * 
 *
 * @export
 * @interface InlineResponse200132
 */
export interface InlineResponse200132 {

    /**
     * @type {string}
     * @memberof InlineResponse200132
     * @example Axs*90
     */
    projectId: string;

    /**
     * @type {Sapiv1stakingproductListDetail}
     * @memberof InlineResponse200132
     */
    detail: Sapiv1stakingproductListDetail;

    /**
     * @type {Sapiv1stakingproductListQuota}
     * @memberof InlineResponse200132
     */
    quota: Sapiv1stakingproductListQuota;
}
