/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse200223ReceiverInfoExtend } from './inline-response200223-receiver-info-extend';
 /**
 * 
 *
 * @export
 * @interface InlineResponse200223ReceiverInfo
 */
export interface InlineResponse200223ReceiverInfo {

    /**
     * @type {string}
     * @memberof InlineResponse200223ReceiverInfo
     * @example Alan
     */
    name: string;

    /**
     * @type {string}
     * @memberof InlineResponse200223ReceiverInfo
     * @example MERCHANT
     */
    type: string;

    /**
     * @type {string}
     * @memberof InlineResponse200223ReceiverInfo
     * @example alan@test.com
     */
    email: string;

    /**
     * @type {string}
     * @memberof InlineResponse200223ReceiverInfo
     * @example 34355667
     */
    binanceId: string;

    /**
     * @type {string}
     * @memberof InlineResponse200223ReceiverInfo
     * @example 21326891
     */
    accountId: string;

    /**
     * @type {string}
     * @memberof InlineResponse200223ReceiverInfo
     * @example 1
     */
    countryCode: string;

    /**
     * @type {string}
     * @memberof InlineResponse200223ReceiverInfo
     * @example 8057651210
     */
    phoneNumber: string;

    /**
     * @type {string}
     * @memberof InlineResponse200223ReceiverInfo
     * @example US
     */
    mobileCode: string;

    /**
     * @type {Array<InlineResponse200223ReceiverInfoExtend>}
     * @memberof InlineResponse200223ReceiverInfo
     */
    extend?: Array<InlineResponse200223ReceiverInfoExtend>;
}
