/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Sapiv1blvttokenInfoCurrentBaskets } from './sapiv1blvttoken-info-current-baskets';
 /**
 * 
 *
 * @export
 * @interface InlineResponse200172
 */
export interface InlineResponse200172 {

    /**
     * @type {string}
     * @memberof InlineResponse200172
     * @example BTCDOWN
     */
    tokenName: string;

    /**
     * @type {string}
     * @memberof InlineResponse200172
     * @example 3X Short Bitcoin Token
     */
    description: string;

    /**
     * @type {string}
     * @memberof InlineResponse200172
     * @example BTC
     */
    underlying: string;

    /**
     * @type {string}
     * @memberof InlineResponse200172
     * @example 717953.95
     */
    tokenIssued: string;

    /**
     * @type {string}
     * @memberof InlineResponse200172
     * @example -821.474 BTCUSDT Futures
     */
    basket: string;

    /**
     * @type {Array<Sapiv1blvttokenInfoCurrentBaskets>}
     * @memberof InlineResponse200172
     */
    currentBaskets: Array<Sapiv1blvttokenInfoCurrentBaskets>;

    /**
     * @type {string}
     * @memberof InlineResponse200172
     * @example 4.79
     */
    nav: string;

    /**
     * @type {string}
     * @memberof InlineResponse200172
     * @example -2.316
     */
    realLeverage: string;

    /**
     * @type {string}
     * @memberof InlineResponse200172
     * @example 0.001020
     */
    fundingRate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200172
     * @example 0.0001
     */
    dailyManagementFee: string;

    /**
     * @type {string}
     * @memberof InlineResponse200172
     * @example 0.0010
     */
    purchaseFeePct: string;

    /**
     * @type {string}
     * @memberof InlineResponse200172
     * @example 100000.00
     */
    dailyPurchaseLimit: string;

    /**
     * @type {string}
     * @memberof InlineResponse200172
     * @example 0.0010
     */
    redeemFeePct: string;

    /**
     * @type {string}
     * @memberof InlineResponse200172
     * @example 1000000.00
     */
    dailyRedeemLimit: string;

    /**
     * @type {number}
     * @memberof InlineResponse200172
     * @example 1583127900000
     */
    timestamp: number;
}
