/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse20025
 */
export interface InlineResponse20025 {

    /**
     * @type {number}
     * @memberof InlineResponse20025
     * @example 1562046418000
     */
    calcTime: number;

    /**
     * @type {string}
     * @memberof InlineResponse20025
     * @example 0.00333930
     */
    price: string;

    /**
     * @type {string}
     * @memberof InlineResponse20025
     * @example BNBBTC
     */
    symbol: string;
}
