/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200197Rows
 */
export interface InlineResponse200197Rows {

    /**
     * @type {string}
     * @memberof InlineResponse200197Rows
     * @example BUSD
     */
    loanCoin: string;

    /**
     * @type {string}
     * @memberof InlineResponse200197Rows
     * @example 0.001503
     */
    flexibleDailyInterestRate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200197Rows
     * @example 0.548595
     */
    flexibleYearlyInterestRate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200197Rows
     * @example 0.000136
     */
    _30dDailyInterestRate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200197Rows
     * @example 0.03450
     */
    _30dYearlyInterestRate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200197Rows
     * @example 0.000145
     */
    _60dDailyInterestRate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200197Rows
     * @example 0.04103
     */
    _60dYearlyInterestRate: string;

    /**
     * @type {string}
     * @memberof InlineResponse200197Rows
     * @example 100
     */
    minLimit: string;

    /**
     * @type {string}
     * @memberof InlineResponse200197Rows
     * @example 1000000
     */
    maxLimit: string;

    /**
     * @type {number}
     * @memberof InlineResponse200197Rows
     * @example 1
     */
    vipLevel: number;
}
