/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MarginOcoOrderOrderReports } from './margin-oco-order-order-reports';
import { MarginOcoOrderOrders } from './margin-oco-order-orders';
 /**
 * 
 *
 * @export
 * @interface MarginOcoOrder
 */
export interface MarginOcoOrder {

    /**
     * @type {number}
     * @memberof MarginOcoOrder
     * @example 0
     */
    orderListId: number;

    /**
     * @type {string}
     * @memberof MarginOcoOrder
     * @example OCO
     */
    contingencyType: string;

    /**
     * @type {string}
     * @memberof MarginOcoOrder
     * @example ALL_DONE
     */
    listStatusType: string;

    /**
     * @type {string}
     * @memberof MarginOcoOrder
     * @example ALL_DONE
     */
    listOrderStatus: string;

    /**
     * @type {string}
     * @memberof MarginOcoOrder
     * @example C3wyj4WVEktd7u9aVBRXcN
     */
    listClientOrderId: string;

    /**
     * @type {number}
     * @memberof MarginOcoOrder
     * @example 1574040868128
     */
    transactionTime: number;

    /**
     * @type {string}
     * @memberof MarginOcoOrder
     * @example BNBUSDT
     */
    symbol: string;

    /**
     * @type {boolean}
     * @memberof MarginOcoOrder
     * @example false
     */
    isIsolated: boolean;

    /**
     * @type {Array<MarginOcoOrderOrders>}
     * @memberof MarginOcoOrder
     */
    orders: Array<MarginOcoOrderOrders>;

    /**
     * @type {Array<MarginOcoOrderOrderReports>}
     * @memberof MarginOcoOrder
     */
    orderReports: Array<MarginOcoOrderOrderReports>;
}
