/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface MyTrade
 */
export interface MyTrade {

    /**
     * @type {string}
     * @memberof MyTrade
     * @example BNBBTC
     */
    symbol: string;

    /**
     * Trade id
     *
     * @type {number}
     * @memberof MyTrade
     * @example 28457
     */
    id: number;

    /**
     * @type {number}
     * @memberof MyTrade
     * @example 100234
     */
    orderId: number;

    /**
     * @type {number}
     * @memberof MyTrade
     * @example -1
     */
    orderListId: number;

    /**
     * Price
     *
     * @type {string}
     * @memberof MyTrade
     * @example 4.00000100
     */
    price: string;

    /**
     * Amount of base asset
     *
     * @type {string}
     * @memberof MyTrade
     * @example 12.00000000
     */
    qty: string;

    /**
     * Amount of quote asset
     *
     * @type {string}
     * @memberof MyTrade
     * @example 48.000012
     */
    quoteQty: string;

    /**
     * @type {string}
     * @memberof MyTrade
     * @example 10.10000000
     */
    commission: string;

    /**
     * @type {string}
     * @memberof MyTrade
     * @example BNB
     */
    commissionAsset: string;

    /**
     * Trade timestamp
     *
     * @type {number}
     * @memberof MyTrade
     * @example 1499865549590
     */
    time: number;

    /**
     * @type {boolean}
     * @memberof MyTrade
     * @example false
     */
    isBuyer: boolean;

    /**
     * @type {boolean}
     * @memberof MyTrade
     * @example false
     */
    isMaker: boolean;

    /**
     * @type {boolean}
     * @memberof MyTrade
     */
    isBestMatch: boolean;
}
