/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OcoOrderOrderReports } from './oco-order-order-reports';
import { OcoOrderOrders } from './oco-order-orders';
 /**
 * 
 *
 * @export
 * @interface OcoOrder
 */
export interface OcoOrder {

    /**
     * @type {number}
     * @memberof OcoOrder
     * @example 1929
     */
    orderListId: number;

    /**
     * @type {string}
     * @memberof OcoOrder
     * @example OCO
     */
    contingencyType: string;

    /**
     * @type {string}
     * @memberof OcoOrder
     * @example ALL_DONE
     */
    listStatusType: string;

    /**
     * @type {string}
     * @memberof OcoOrder
     * @example ALL_DONE
     */
    listOrderStatus: string;

    /**
     * @type {string}
     * @memberof OcoOrder
     * @example C3wyj4WVEktd7u9aVBRXcN
     */
    listClientOrderId: string;

    /**
     * @type {number}
     * @memberof OcoOrder
     * @example 1574040868128
     */
    transactionTime: number;

    /**
     * @type {string}
     * @memberof OcoOrder
     * @example BNBBTC
     */
    symbol: string;

    /**
     * @type {Array<OcoOrderOrders>}
     * @memberof OcoOrder
     * @example [{"symbol":"BNBBTC","orderId":2,"clientOrderId":"pO9ufTiFGg3nw2fOdgeOXa"},{"symbol":"BNBBTC","orderId":3,"clientOrderId":"TXOvglzXuaubXAaENpaRCB"}]
     */
    orders: Array<OcoOrderOrders>;

    /**
     * @type {Array<OcoOrderOrderReports>}
     * @memberof OcoOrder
     * @example [{"symbol":"BNBBTC","origClientOrderId":"pO9ufTiFGg3nw2fOdgeOXa","orderId":2,"orderListId":0,"clientOrderId":"unfWT8ig8i0uj6lPuYLez6","price":"1.00000000","origQty":"10.00000000","executedQty":"0.00000000","cummulativeQuoteQty":"0.00000000","status":"CANCELED","timeInForce":"GTC","type":"STOP_LOSS_LIMIT","side":"SELL","stopPrice":"1.00000000","transactTime":1688005070874},{"symbol":"BNBBTC","origClientOrderId":"TXOvglzXuaubXAaENpaRCB","orderId":3,"orderListId":0,"clientOrderId":"unfWT8ig8i0uj6lPuYLez6","price":"3.00000000","origQty":"10.00000000","executedQty":"0.00000000","cummulativeQuoteQty":"0.00000000","status":"CANCELED","timeInForce":"GTC","type":"LIMIT_MAKER","side":"SELL","selfTradePreventionMode":"NONE","transactTime":1688005070874}]
     */
    orderReports: Array<OcoOrderOrderReports>;
}
