/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Order
 */
export interface Order {

    /**
     * @type {string}
     * @memberof Order
     * @example BNBBTC
     */
    symbol: string;

    /**
     * @type {string}
     * @memberof Order
     * @example msXkySR3u5uYwpvRMFsi3u
     */
    origClientOrderId: string;

    /**
     * @type {number}
     * @memberof Order
     * @example 28
     */
    orderId: number;

    /**
     * Unless OCO, value will be -1
     *
     * @type {number}
     * @memberof Order
     * @example -1
     */
    orderListId: number;

    /**
     * @type {string}
     * @memberof Order
     * @example 6gCrw2kRUAF9CvJDGP16IP
     */
    clientOrderId: string;

    /**
     * @type {number}
     * @memberof Order
     * @example 1507725176595
     */
    transactTime: number;

    /**
     * @type {string}
     * @memberof Order
     * @example 1.00000000
     */
    price: string;

    /**
     * @type {string}
     * @memberof Order
     * @example 10.00000000
     */
    origQty: string;

    /**
     * @type {string}
     * @memberof Order
     * @example 10.00000000
     */
    executedQty: string;

    /**
     * @type {string}
     * @memberof Order
     * @example 10.00000000
     */
    cummulativeQuoteQty: string;

    /**
     * @type {string}
     * @memberof Order
     * @example FILLED
     */
    status: string;

    /**
     * @type {string}
     * @memberof Order
     * @example GTC
     */
    timeInForce: string;

    /**
     * @type {string}
     * @memberof Order
     * @example LIMIT
     */
    type: string;

    /**
     * @type {string}
     * @memberof Order
     * @example SELL
     */
    side: string;

    /**
     * @type {string}
     * @memberof Order
     * @example NONE
     */
    selfTradePreventionMode: string;
}
