/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface OrderResponseAck
 */
export interface OrderResponseAck {

    /**
     * @type {string}
     * @memberof OrderResponseAck
     * @example BTCUSDT
     */
    symbol: string;

    /**
     * @type {number}
     * @memberof OrderResponseAck
     * @example 28
     */
    orderId: number;

    /**
     * @type {number}
     * @memberof OrderResponseAck
     * @example -1
     */
    orderListId: number;

    /**
     * @type {string}
     * @memberof OrderResponseAck
     * @example 6gCrw2kRUAF9CvJDGP16IP
     */
    clientOrderId: string;

    /**
     * @type {number}
     * @memberof OrderResponseAck
     * @example 1507725176595
     */
    transactTime: number;
}
