/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface OrderResponseFullFills
 */
export interface OrderResponseFullFills {

    /**
     * @type {string}
     * @memberof OrderResponseFullFills
     * @example 4000.00000000
     */
    price: string;

    /**
     * @type {string}
     * @memberof OrderResponseFullFills
     * @example 1.00000000
     */
    qty: string;

    /**
     * @type {string}
     * @memberof OrderResponseFullFills
     * @example 4.00000000
     */
    commission: string;

    /**
     * @type {string}
     * @memberof OrderResponseFullFills
     * @example USDT
     */
    commissionAsset: string;
}
