/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Sapiv1bswappoolConfigureLiquidity
 */
export interface Sapiv1bswappoolConfigureLiquidity {

    /**
     * \"NA\" if pool is an innovation pool
     *
     * @type {number}
     * @memberof Sapiv1bswappoolConfigureLiquidity
     * @example 2000
     */
    constantA: number;

    /**
     * @type {number}
     * @memberof Sapiv1bswappoolConfigureLiquidity
     * @example 0.1
     */
    minRedeemShare: number;

    /**
     * The swap proceeds only when the slippage is within the set range
     *
     * @type {number}
     * @memberof Sapiv1bswappoolConfigureLiquidity
     * @example 0.2
     */
    slippageTolerance: number;
}
