/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Sapiv1marginleverageBracketBrackets
 */
export interface Sapiv1marginleverageBracketBrackets {

    /**
     * @type {number}
     * @memberof Sapiv1marginleverageBracketBrackets
     * @example 10
     */
    leverage?: number;

    /**
     * @type {number}
     * @memberof Sapiv1marginleverageBracketBrackets
     * @example 1000000
     */
    maxDebt?: number;

    /**
     * @type {number}
     * @memberof Sapiv1marginleverageBracketBrackets
     * @example 0.02
     */
    maintenanceMarginRate?: number;

    /**
     * @type {number}
     * @memberof Sapiv1marginleverageBracketBrackets
     * @example 0.1112
     */
    initialMarginRate?: number;

    /**
     * @type {number}
     * @memberof Sapiv1marginleverageBracketBrackets
     * @example 60000
     */
    fastNum?: number;
}
