/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Sapiv1blvttokenInfoCurrentBaskets
 */
export interface Sapiv1blvttokenInfoCurrentBaskets {

    /**
     * @type {string}
     * @memberof Sapiv1blvttokenInfoCurrentBaskets
     * @example BTCUSDT
     */
    symbol: string;

    /**
     * @type {string}
     * @memberof Sapiv1blvttokenInfoCurrentBaskets
     * @example -1183.984
     */
    amount: string;

    /**
     * @type {string}
     * @memberof Sapiv1blvttokenInfoCurrentBaskets
     * @example -22871089.96704
     */
    notionalValue: string;
}
