/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Sapiv1lendingautoinvestrebalancehistoryTransactionDetails
 */
export interface Sapiv1lendingautoinvestrebalancehistoryTransactionDetails {

    /**
     * @type {string}
     * @memberof Sapiv1lendingautoinvestrebalancehistoryTransactionDetails
     * @example BTC
     */
    asset: string;

    /**
     * @type {number}
     * @memberof Sapiv1lendingautoinvestrebalancehistoryTransactionDetails
     * @example 1648378800000
     */
    transactionDateTime: number;

    /**
     * @type {string}
     * @memberof Sapiv1lendingautoinvestrebalancehistoryTransactionDetails
     * @example BUY
     */
    rebalanceDirection: string;

    /**
     * @type {string}
     * @memberof Sapiv1lendingautoinvestrebalancehistoryTransactionDetails
     * @example 0.005
     */
    rebalanceAmount: string;
}
