/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SnapshotFuturesDataAssets } from './snapshot-futures-data-assets';
import { SnapshotFuturesDataPosition } from './snapshot-futures-data-position';
 /**
 * 
 *
 * @export
 * @interface SnapshotFuturesData
 */
export interface SnapshotFuturesData {

    /**
     * @type {Array<SnapshotFuturesDataAssets>}
     * @memberof SnapshotFuturesData
     */
    assets: Array<SnapshotFuturesDataAssets>;

    /**
     * @type {Array<SnapshotFuturesDataPosition>}
     * @memberof SnapshotFuturesData
     */
    position: Array<SnapshotFuturesDataPosition>;
}
