/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SnapshotSpotSnapshotVos } from './snapshot-spot-snapshot-vos';
 /**
 * 
 *
 * @export
 * @interface SnapshotSpot
 */
export interface SnapshotSpot {

    /**
     * @type {number}
     * @memberof SnapshotSpot
     * @example 200
     */
    code: number;

    /**
     * @type {string}
     * @memberof SnapshotSpot
     */
    msg: string;

    /**
     * @type {Array<SnapshotSpotSnapshotVos>}
     * @memberof SnapshotSpot
     */
    snapshotVos: Array<SnapshotSpotSnapshotVos>;
}
