/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SnapshotSpotDataBalances
 */
export interface SnapshotSpotDataBalances {

    /**
     * @type {string}
     * @memberof SnapshotSpotDataBalances
     * @example BTC
     */
    asset: string;

    /**
     * @type {string}
     * @memberof SnapshotSpotDataBalances
     * @example 0.2
     */
    free: string;

    /**
     * @type {string}
     * @memberof SnapshotSpotDataBalances
     * @example 0.001
     */
    locked: string;
}
