/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SnapshotMarginDataUserAssets } from './snapshot-margin-data-user-assets';
 /**
 * 
 *
 * @export
 * @interface SnapshotMarginData
 */
export interface SnapshotMarginData {

    /**
     * @type {string}
     * @memberof SnapshotMarginData
     * @example 2748.02909813
     */
    marginLevel: string;

    /**
     * @type {string}
     * @memberof SnapshotMarginData
     * @example 0.00274803
     */
    totalAssetOfBtc: string;

    /**
     * @type {string}
     * @memberof SnapshotMarginData
     * @example 0.00000100
     */
    totalLiabilityOfBtc: string;

    /**
     * @type {string}
     * @memberof SnapshotMarginData
     * @example 0.00274750
     */
    totalNetAssetOfBtc: string;

    /**
     * @type {Array<SnapshotMarginDataUserAssets>}
     * @memberof SnapshotMarginData
     */
    userAssets: Array<SnapshotMarginDataUserAssets>;
}
