/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SubAccountUSDTFuturesSummaryFutureAccountSummaryRespSubAccountList
 */
export interface SubAccountUSDTFuturesSummaryFutureAccountSummaryRespSubAccountList {

    /**
     * @type {string}
     * @memberof SubAccountUSDTFuturesSummaryFutureAccountSummaryRespSubAccountList
     * @example 123@test.com
     */
    email: string;

    /**
     * @type {string}
     * @memberof SubAccountUSDTFuturesSummaryFutureAccountSummaryRespSubAccountList
     * @example 9.00000000
     */
    totalInitialMargin: string;

    /**
     * @type {string}
     * @memberof SubAccountUSDTFuturesSummaryFutureAccountSummaryRespSubAccountList
     * @example 0.00000000
     */
    totalMaintenanceMargin: string;

    /**
     * @type {string}
     * @memberof SubAccountUSDTFuturesSummaryFutureAccountSummaryRespSubAccountList
     * @example 22.12659734
     */
    totalMarginBalance: string;

    /**
     * @type {string}
     * @memberof SubAccountUSDTFuturesSummaryFutureAccountSummaryRespSubAccountList
     * @example 9.00000000
     */
    totalOpenOrderInitialMargin: string;

    /**
     * @type {string}
     * @memberof SubAccountUSDTFuturesSummaryFutureAccountSummaryRespSubAccountList
     * @example 0.00000000
     */
    totalPositionInitialMargin: string;

    /**
     * @type {string}
     * @memberof SubAccountUSDTFuturesSummaryFutureAccountSummaryRespSubAccountList
     * @example 0.00000000
     */
    totalUnrealizedProfit: string;

    /**
     * @type {string}
     * @memberof SubAccountUSDTFuturesSummaryFutureAccountSummaryRespSubAccountList
     * @example 22.12659734
     */
    totalWalletBalance: string;

    /**
     * The sum of BUSD and USDT
     *
     * @type {string}
     * @memberof SubAccountUSDTFuturesSummaryFutureAccountSummaryRespSubAccountList
     * @example USD
     */
    asset: string;
}
