/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos
 */
export interface SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos {

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos
     * @example 9975.12000
     */
    entryPrice: string;

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos
     * @example 9973.50770517
     */
    markPrice: string;

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos
     * @example 20
     */
    leverage: string;

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos
     * @example false
     */
    isolated: string;

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos
     * @example 9973.50770517
     */
    isolatedWallet: string;

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos
     * @example 0.00000000
     */
    isolatedMargin: string;

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos
     * @example false
     */
    isAutoAddMargin: string;

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos
     * @example BOTH
     */
    positionSide: string;

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos
     * @example 1.230
     */
    positionAmount: string;

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos
     * @example BTCUSD_201225
     */
    symbol: string;

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesPositionRiskDeliveryPositionRiskVos
     * @example -0.01612295
     */
    unrealizedProfit: string;
}
