/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SubAccountCOINFuturesDetailsAssets
 */
export interface SubAccountCOINFuturesDetailsAssets {

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesDetailsAssets
     * @example BTC
     */
    asset: string;

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesDetailsAssets
     * @example 0.00000000
     */
    initialMargin: string;

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesDetailsAssets
     * @example 0.00000000
     */
    maintenanceMargin: string;

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesDetailsAssets
     * @example 0.88308000
     */
    marginBalance: string;

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesDetailsAssets
     * @example 0.88308000
     */
    maxWithdrawAmount: string;

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesDetailsAssets
     * @example 0.00000000
     */
    openOrderInitialMargin: string;

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesDetailsAssets
     * @example 0.00000000
     */
    positionInitialMargin: string;

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesDetailsAssets
     * @example 0.00000000
     */
    unrealizedProfit: string;

    /**
     * @type {string}
     * @memberof SubAccountCOINFuturesDetailsAssets
     * @example 0.88308000
     */
    walletBalance: string;
}
