/* tslint:disable */
/* eslint-disable */
/**
 * Binance Public Spot API
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Ticker
 */
export interface Ticker {

    /**
     * @type {string}
     * @memberof Ticker
     * @example BNBBTC
     */
    symbol: string;

    /**
     * @type {string}
     * @memberof Ticker
     * @example 0.17160000
     */
    priceChange: string;

    /**
     * @type {string}
     * @memberof Ticker
     * @example 1.060
     */
    priceChangePercent: string;

    /**
     * @type {string}
     * @memberof Ticker
     * @example 16.35920000
     */
    prevClosePrice: string;

    /**
     * @type {string}
     * @memberof Ticker
     * @example 27.84000000
     */
    lastPrice: string;

    /**
     * @type {string}
     * @memberof Ticker
     * @example 16.34488284
     */
    bidPrice: string;

    /**
     * @type {string}
     * @memberof Ticker
     * @example 16.34488284
     */
    bidQty: string;

    /**
     * @type {string}
     * @memberof Ticker
     * @example 16.35920000
     */
    askPrice: string;

    /**
     * @type {string}
     * @memberof Ticker
     * @example 25.06000000
     */
    askQty: string;

    /**
     * @type {string}
     * @memberof Ticker
     * @example 16.18760000
     */
    openPrice: string;

    /**
     * @type {string}
     * @memberof Ticker
     * @example 16.55000000
     */
    highPrice: string;

    /**
     * @type {string}
     * @memberof Ticker
     * @example 16.16940000
     */
    lowPrice: string;

    /**
     * @type {string}
     * @memberof Ticker
     * @example 1678279.95000000
     */
    volume: string;

    /**
     * @type {string}
     * @memberof Ticker
     * @example 27431289.14792300
     */
    quoteVolume: string;

    /**
     * @type {number}
     * @memberof Ticker
     * @example 1592808788637
     */
    openTime: number;

    /**
     * @type {number}
     * @memberof Ticker
     * @example 1592895188637
     */
    closeTime: number;

    /**
     * @type {number}
     * @memberof Ticker
     * @example 62683296
     */
    firstId: number;

    /**
     * @type {number}
     * @memberof Ticker
     * @example 62739253
     */
    lastId: number;

    /**
     * @type {number}
     * @memberof Ticker
     * @example 55958
     */
    count: number;
}
